### PR TITLE
include LICENSE to sub-crates

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <ignatenko@src.gnome.org>

### CODE REVIEW

**Comment by EPashkin** [comment]
It was symbolic link?
This don't work on Windows.

**Comment by ignatenkobrain** [comment]
@EPashkin replaced with real copy.

**Comment by EPashkin** [comment]
@ignatenkobrain Now it looks normal.
Any reason to do that without copying COPYRIGHT ?

**Comment by EPashkin** [comment]
As I understand source can't be published as separate parts.

**Comment by EPashkin** [comment]
@GuillaumeGomez, maybe we need merge this.
I still has no idea what to do with "COPYRIGHT" file, but including "LICENSE" in published packages is IMHO right way.

**Comment by GuillaumeGomez** [comment]
Completely missed it. Merging. Thanks!

**Pull request merged**
