### PR TITLE
Gir files zesty

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir-files/issues/1

Still in WIP so ignore first line change

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
```
error[E0004]: non-exhaustive patterns: `DefaultModMask` not covered
   --> /home/travis/.cargo/git/checkouts/gdk-0e2106e2e12a0cc1/68d624b5a4d7ffa13518229ec249cd566a93143e/src/auto/enums.rs:424:15
    |
424 |         match value {
    |               ^^^^^ pattern `DefaultModMask` not covered
error: aborting due to previous error
```

And since I need this PR to get merged to merge the others. :-/

**Comment by EPashkin** [comment]
Ready to merge and IMHO it must builds

**Comment by EPashkin** [comment]
Was wrong, beta newer don't builds due cargo bug, and others due gdk

**Comment by EPashkin** [comment]
This still need to be merged

**Comment by GuillaumeGomez** [comment]
My bad. Thanks!

**Pull request merged**
