### PR TITLE
Add dox feature

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
One a day seems like a good pace haha.

**Comment by EPashkin** [comment]
No changes in `lib.rs` namely `pub struct GHookList`

**Comment by GuillaumeGomez** [comment]
Didn't understood your comment. :-/

**Comment by EPashkin** [comment]
There no `dox` in code, so not understand why you add features without code regen,

**Comment by GuillaumeGomez** [comment]
Oh damn, I thought it had already been done... I'll regen this evening then.

**Comment by GuillaumeGomez** [comment]
Regen.

**Comment by EPashkin** [comment]
Regen removed dox feature from Cargo.toml's

**Comment by GuillaumeGomez** [comment]
We regen the `Cargo.toml`? Damn, I need to fix the generation then. Where is it?

**Comment by EPashkin** [comment]
https://github.com/gtk-rs/gir/blob/master/src/codegen/sys/cargo_toml.rs

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by EPashkin** [comment]
👍 Thanks

**Pull request merged**
