### PR TITLE
Fix build_version.rs

### PR DESCRIPTION
**Pull request by EPashkin**
Part of #167 (comment)
Apply of gtk-rs/gir#917

cc @sdroege , @GuillaumeGomez , @kinnison

### CODE REVIEW

**Comment by EPashkin** [comment]
Now we in deadlock with https://github.com/gtk-rs/examples/pull/310

**Comment by sdroege** [comment]
@GuillaumeGomez please merge to unblock part of the breakage at least :)

**Comment by EPashkin** [comment]
CI passed

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
