### PR TITLE
Regenerate glib-sys with latest GIR

### PR DESCRIPTION
**Pull request by sdroege**
See https://github.com/gtk-rs/gir/pull/466

### CODE REVIEW

**Comment by EPashkin** [comment]
Please, add other changes even if it only headers

**Comment by sdroege** [comment]
Done

**Comment by EPashkin** [comment]
Thanks, 👍 from me

**Comment by sdroege** [comment]
@GuillaumeGomez Good to merge then I guess :)

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by sdroege** [comment]
Thansk, I can get rid of my workaround :)

**Pull request merged**
