### PR TITLE
Crate

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Last step!

cc @EPashkin @sdroege (and you too @RazrFalcon ;) )

### CODE REVIEW

**Comment by EPashkin** [comment]
We still don't finished regen for all crates.

**Comment by GuillaumeGomez** [comment]
It's not a full release, it's just for `pango-cairo`.

**Comment by RazrFalcon** [comment]
It's `pangocairo` not `pango-cairo`...

**Comment by GuillaumeGomez** [comment]
I gave this name to the package: https://github.com/gtk-rs/sys/pull/66/files#diff-190780c5281d486a0ff8ae0d0f295725R20

Maybe I should rename the folder though...

**Comment by RazrFalcon** [comment]
You mean crate? It's `pangocairo`.

**Comment by GuillaumeGomez** [comment]
https://github.com/gtk-rs/pango-cairo/blob/master/Cargo.toml#L2

**Comment by EPashkin** [comment]
@GuillaumeGomez Ah, I thought it full update.
If only `pangocairo-sys` will be published then 👍

**Comment by GuillaumeGomez** [comment]
@EPashkin: And `pangocairo` as well. But for the big release, I'm still waiting for everything to be finished. Once you and @sdroege give me the go, then I'll make the release. :)

**Comment by RazrFalcon** [comment]
@GuillaumeGomez I hope Google will understand `pangocairo rust` as `pango-cairo rust`...

**Comment by GuillaumeGomez** [comment]
Ok, I update the name of the folder and of the repository. :p

**Comment by sdroege** [comment]
Go for it :) from my side we're ready for a full release also

**Comment by GuillaumeGomez** [comment]
Well, I'm not ready yet for the full release. If @EPashkin is ok as well, then I'll try (I won't be home so can't guarantee it) to make a new release.

**Comment by EPashkin** [comment]
Seems thing that need make before full release:
- do full regen in sys to make all headers same (not fully necessary)
- add dox to cairo, gdk, sourceview
- fix dox in gtk\Cargo.toml (add gtk-sys/dox, gdk/dox)

PS. Folder rename IMHO better do in master.

**Comment by EPashkin** [comment]
Ignore PS, looked only github, and missed that you do it in master

**Comment by GuillaumeGomez** [comment]
Hehe. And I agree for all listed points.

**Comment by RazrFalcon** [comment]
@GuillaumeGomez please notify me when it would be safe to remove my github repo of `pangocairo`.

**Comment by GuillaumeGomez** [comment]
Once https://github.com/gtk-rs/pangocairo/pull/2 is merged.

**Comment by RazrFalcon** [comment]
Got it. Subscribed.

**Pull request merged**
