### PR TITLE
Update all versions

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by EPashkin** [comment]
👍 Thanks

**Comment by EPashkin** [comment]
IMHO If you remove version from git dependencies it can even build without error (cairo-rs-sys)

**Comment by GuillaumeGomez** [comment]
I'll start merging cairo's PR then restart tests in here and we'll go up like this. ;)

**Comment by EPashkin** [comment]
Your way will be same errors for other git dependencies.

**Comment by GuillaumeGomez** [comment]
I merged cairo (I'll restart CI for it later).

**Comment by EPashkin** [comment]
But as error be in my way too as it build against gtk with versioned dependencies

**Comment by GuillaumeGomez** [comment]
Oh damn, we need to merge everything to test! Well, then let's merge...

**Comment by EPashkin** [comment]
Hm, I don't see gdk PR but see update branch in your repo

**Comment by GuillaumeGomez** [comment]
:-.

**Comment by EPashkin** [comment]
I confirm that examples now builds locally

**Comment by GuillaumeGomez** [comment]
I restarted all builds, they seem to succeed as well. :)

**Pull request merged**
