### PR TITLE
Print some additional output on macOS if pkg-config fails

### PR DESCRIPTION
**Pull request by sdroege**
homebrew is broken by design and requires manual user-intervention.
See https://github.com/Homebrew/homebrew-core/issues/40179 for more
details.

Fixes https://github.com/gtk-rs/cairo/issues/263

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Fine enough for me then, thanks!

**Comment by sdroege** [comment]
So problem now is that `build.rs` is autogenerated. Should we add a special case to gir for this if the crate name is `gobject-sys`? @EPashkin ideas? :)

**Comment by EPashkin** [comment]
@sdroege IMHO adding this for `ns.sys_crate_name=="gobject-sys"` is good idea,
I will add it

**Comment by sdroege** [comment]
@EPashkin Updated the PR. Thanks!

**Comment by GuillaumeGomez** [comment]
👍

**Comment by EPashkin** [comment]
@sdroege Thanks, 👍 after all version.txt updated

**Comment by sdroege** [comment]
Regenerated all the version.txt. Wanted to keep the churn lower but the CI does not like that :)

**Comment by sdroege** [comment]
@GuillaumeGomez all green

**Pull request merged**
