### PR TITLE
Add correct versions for get_type functions

### PR DESCRIPTION
**Pull request by sdroege**
See individual  commits. I'll go through the other libraries later, this is only pango so far.

### CODE REVIEW

**Comment by sdroege** [comment]
CC @EPashkin @GuillaumeGomez

**Comment by sdroege** [comment]
And some more (glib/gio/pango done). There are quite a lot of such cases... I wonder why nobody noticed before.

**Comment by sdroege** [comment]
Also as a result of this we need to fix the non-sys bindings with the same configurations too, but they all need to be regenerated anyway. I'll take care of that.

**Comment by sdroege** [comment]
@EPashkin @GuillaumeGomez This is ready for review and merging now. Once it's in I will create PRs for all the affected modules.

**Comment by sdroege** [comment]
This needs another look at before merging.

**Comment by EPashkin** [comment]
@sdroege LGFM, Especially gdx11 minimum version

**Comment by sdroege** [comment]
Thanks for checking, but please don't merge yet. I want to do another check here first and also make sure I have local branches for all the other repositories ready :)

**Pull request merged**
