### PR TITLE
Regen for fixing tests errors

### PR DESCRIPTION
**Pull request by EPashkin**
Regenerate with https://github.com/gtk-rs/gir/pull/658 and https://github.com/gtk-rs/gir/pull/659

cc @GuillaumeGomez , @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
Travis failed due strange long build.

**Comment by sdroege** [comment]
Seems fine to me. Maybe trigger a retry on travis

**Comment by GuillaumeGomez** [comment]
Looks good to me as well! (restarted CI too)

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
