### PR TITLE
Upgrade to bitflags v0.7

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gtk/issues/410
WIP

### CODE REVIEW

**Comment by EPashkin** [comment]
Tried syncronize with main crates and use `bitflags = 0.5` but it won't build with strange errors, so I changed to latest.
```
error[E0412]: type name `c_uint` is undefined or not in scope
    --> src\lib.rs:2056:37
     |
2056 |     pub flags GtkUIManagerItemType: c_uint {
     |                                     ^^^^^^ undefined or not in scope
     |
     = help: you can import several candidates into scope (`use ...;`):
     = help:   `libc::c_uint`
     = help:   `std::os::raw::c_uint`

error: aborting due to 92 previous errors

error: Could not compile `gtk-sys`.
```

**Comment by EPashkin** [comment]
Seems v0.7 won't work on stable (https://ci.appveyor.com/project/GuillaumeGomez/sys/build/1.0.52):
```
<bitflags macros>:89:15: 90:32 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:89  # [ inline ] fn bitor_assign ( & mut self , other : $ BitFlags ) {
<bitflags macros>:90 self . bits |= other . bits ; } } impl $ crate:: __core:: ops:: BitXor for $
<bitflags macros>:8:24: 10:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:134:1: 136:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
C:\projects\sys\glib-sys\src\lib.rs:1362:1: 1377:2 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:86:59: 87:18 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
```
v0.6 produces same error as v0.5.
I close this PR and https://github.com/gtk-rs/gir/pull/296

**Comment by EPashkin** [comment]
As https://github.com/rust-lang-nursery/bitflags/pull/47 says, `bitflags v0.7` starting work with rust 1.8 stable
and we forgot to upgrade `appveyor.xml` and it uses rust 1.6.
Doing next try

**Comment by EPashkin** [comment]
@GuillaumeGomez, good thing that nightly finally fixed, bad thing that it's error go to not only beta but also to stable.
So upgraded appveyor fails too :cry:

**Comment by GuillaumeGomez** [comment]
Why am I not surprised? 😆

**Comment by EPashkin** [comment]
@GuillaumeGomez, restart this too, please.
But do not merge if passed

**Comment by GuillaumeGomez** [comment]
Yes sir!

**Comment by EPashkin** [comment]
Closing in favor of #45

**Pull request closed without merging**
