### PR TITLE
Include missing headers for ABI checks.

### PR DESCRIPTION
**Pull request by tmiasko**

### CODE REVIEW

**Comment by tmiasko** [comment]
@EPashkin, @GuillaumeGomez ping?

**Comment by GuillaumeGomez** [comment]
Seems good to me, thanks!

**Comment by EPashkin** [comment]
@tmiasko Thanks for remembering about this PR, 👍

**Comment by EPashkin** [comment]
I think we can ignore regen check now and merge, as we need update sys if https://github.com/gtk-rs/gir/pull/675 accepted.

**Comment by GuillaumeGomez** [comment]
I was about to comment about it. This PR doesn't impact it so let's ignore that. I'll just merge.

**Pull request merged**
