### PR TITLE
WIP: Fix name for Cairo.FontType

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/sys/issues/116

Need update gir-files

cc @GuillaumeGomez , @sdroege , @vhdirk

### CODE REVIEW

**Comment by sdroege** [comment]
:+1: 

Should never ever pass Rust enums via FFI

**Comment by sdroege** [comment]
Also happened in the gstreamer bindings CI because of an example using pangocairo: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/jobs/48916

```
error[E0433]: failed to resolve. Could not find `enums` in `cairo`
  --> .cargo_cache/git/checkouts/sys-5eecc06807450db7/e10e6ef/pangocairo-sys/src/lib.rs:74:68
   |
74 |     pub fn pango_cairo_font_map_new_for_font_type(fonttype: cairo::enums::FontType) -> *mut pango::PangoFontMap;
   |                                                                    ^^^^^ Could not find `enums` in `cairo`

error[E0433]: failed to resolve. Could not find `enums` in `cairo`
  --> .cargo_cache/git/checkouts/sys-5eecc06807450db7/e10e6ef/pangocairo-sys/src/lib.rs:76:90
   |
76 |     pub fn pango_cairo_font_map_get_font_type(fontmap: *mut PangoCairoFontMap) -> cairo::enums::FontType;
   |                                                                                          ^^^^^ Could not find `enums` in `cairo`
```

**Comment by sdroege** [comment]
Why was this not caught by travis here btw?

**Comment by GuillaumeGomez** [comment]
Meanwhile, let's merge this one. Thanks @EPashkin!

**Comment by EPashkin** [comment]
It was still WIP :(

**Comment by EPashkin** [comment]
Seems it not problem, only missing is updating sub-modules

**Pull request merged**
