### PR TITLE
Update to GNOME 3.14 versions

### PR DESCRIPTION
**Pull request by sdroege**
This will break the CI build because the feature flags for the previous versions are gone now. All other crates have to be updated first.

### CODE REVIEW

**Comment by EPashkin** [comment]
Then better start with gtk 😉
Please add link to issue https://github.com/gtk-rs/glib/issues/436 in next PRs.

**Comment by EPashkin** [comment]
*not with gtk but with examples

**Comment by sdroege** [comment]
> *not with gtk but with examples

@EPashkin What would that help? We need to merge everything except for examples first, and then the examples can get green CI and we merge them :)

**Comment by EPashkin** [comment]
I thought that we can do all green update, but now I understand that it umpossible

**Pull request merged**
