### PR TITLE
WIP: Use vcpkg as fallback

### PR DESCRIPTION
**Pull request by EPashkin**
Replace https://github.com/gtk-rs/gtk/pull/753
Part of https://github.com/gtk-rs/gtk/pull/702

This manual change that need be done in gir.

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege 
Currently I plan add option.vcpkg="gtk" to sys config and vcpkg only if it present.
Without this options code will be as in gdk-sys/build.rs.
Note that printing shared libs if pkg-config don't find package will be lost in both cases.
maybe I need just return pkg-config result without "fixing" so user need use `GTK_LIB_DIR` or fix its build environment.

**Comment by GuillaumeGomez** [comment]
Does it help well on windows?

**Comment by EPashkin** [comment]
@GuillaumeGomez On stable-x86_64-pc-windows-msvc it allow to build gtktest example,
it runs if I place it to bin vcpkg folder (I currently don't have it in PATH),
but vcpkg installation need some manual updates to application to works fine:
missing shared icons, glib-2.0 etc.,
maybe I just don't installed something.

**Comment by EPashkin** [comment]
Updated gtk-sys, now cases with vcpkg and without differs only by lines with vcpkg.

**Comment by sdroege** [comment]
> but vcpkg installation need some manual updates to application to works fine:
> missing shared icons, glib-2.0 etc.,
> maybe I just don't installed something.

Yeah that's exactly what @nirbheek mentioned last time `vcpkg` was brought up. It's enough for building GTK but a very minimal cmake-based build system that only does half of the work of a usable GTK installation. Which is why `vcpkg` basing their stuff on meson for GTK and other libraries would be more useful than maintaining another, incomplete build system

**Comment by EPashkin** [comment]
To close issue:
@sdroege think that `vcpkg` incomplete "build system" and we don't need support it.
I not against add `vcpkg` support, but slightly worry about possible effects.
@GuillaumeGomez what you think?

**Comment by GuillaumeGomez** [comment]
You seem to both be negative about it so let's not add it for the moment?

**Comment by sdroege** [comment]
>  @sdroege think that `vcpkg` incomplete "build system" and we don't need support it.

I agree, yes. It's the minimum to build things but it's not actually usable.

**Comment by EPashkin** [comment]
Lets close it then, and please close #753 too.

**Pull request closed without merging**
