### PR TITLE
Regenerate with latest gir

### PR DESCRIPTION
**Pull request by sdroege**
See https://github.com/gtk-rs/gir/pull/412

### CODE REVIEW

**Comment by EPashkin** [comment]
Now all functions in one place. Thanks, @sdroege 
👍

**Comment by sdroege** [comment]
This should be able to go in now, changes since then in gir don't really change anything meaningful

**Comment by EPashkin** [comment]
I agree that nothing actually changed from last gir update, and this PR can be merged as is.

**Comment by EPashkin** [comment]
👍 for this

**Comment by EPashkin** [comment]
Please with restarting travis for https://github.com/gtk-rs/gdk/pull/181 after merge

**Comment by EPashkin** [comment]
Hm, appveyor builds too 🎉

**Comment by sdroege** [comment]
Great :) now only the four or so non-sys regenerate PRs left that depended on this

**Comment by EPashkin** [comment]
Ping @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
