### PR TITLE
Use tempfile in tests

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/pull/870

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

Merging once CI passed.

**Comment by EPashkin** [comment]
Build error seem related to https://github.com/gtk-rs/glib/pull/534
```
error: expected `*` or `+`

   --> /home/travis/.cargo/git/checkouts/glib-928cf7b282977403/5613e42/src/clone.rs:170:24

    |

170 |     ($($(@ $weak:ident)? $variables:ident),+ => $(@default-return $return_value:expr,)? move || $body:block ) => (

    |                        ^

    |

    = note: `?` is not a macro repetition operator in the 2015 edition, but is accepted in the 2018 edition
```

**Comment by GuillaumeGomez** [comment]
I think it might be bound to the rust version. But in any case, I realized we didn't update the rust version in the tests so I opened #155

**Comment by EPashkin** [comment]
Restarted failed jobs

**Comment by EPashkin** [comment]
Oops, forgot to update gtk4 etc.

**Comment by GuillaumeGomez** [comment]
Oh indeed. Good luck updating them. ;)

**Comment by EPashkin** [comment]
Done

**Comment by EPashkin** [comment]
CI passed too

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
