### PR TITLE
Update crate version

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
👍 
@GuillaumeGomez will you yank previous version of gtk-rs-sys?

**Comment by GuillaumeGomez** [comment]
No, it was "correct". This is a bugfix release after all.

**Comment by EPashkin** [comment]
Ok

**Comment by GuillaumeGomez** [comment]
Would you prefer that I yank it?

**Comment by EPashkin** [comment]
Not now, it actually has some many new functions.

**Comment by GuillaumeGomez** [comment]
Ok! Merging then.

**Comment by GuillaumeGomez** [comment]
And now let's make the documentation release.

**Pull request merged**
