### PR TITLE
Depend on cairo-sys when selectin v3_24_2 feature

### PR DESCRIPTION
**Pull request by sdroege**
Fixes https://github.com/gtk-rs/sys/issues/172

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Nice, thanks!

**Comment by sdroege** [comment]
Hm that's not how it works because gir would overwrite the changes. @EPashkin ? :)

**Comment by EPashkin** [comment]
You can change crate to edition2018 and add `use cairo_sys as cairo;` in manual.rs instead

**Comment by sdroege** [comment]
> You can change crate to edition2018 and add `use cairo_sys as cairo;` in manual.rs instead

That doesn't change the problem in `Cargo.toml` though :)

And you can also do `cairo = { package = "cairo-sys-rs", ...}` in `Cargo.toml` instead.

**Comment by EPashkin** [comment]
Cargo.toml for feature "v3_24_2" can be fixed with
```toml
[[feature_dependencies]]
version = "3.24.2"
dependencies = [
  "cairo-sys-rs"
]

```

**Comment by sdroege** [comment]
Oh indeed, thanks :) Done! (Also 2018 edition is not needed for this)

**Comment by EPashkin** [comment]
> 
> 
> Oh indeed, thanks :) Done! (Also 2018 edition is not needed for this)

Only because it already edition2018 😉

**Comment by EPashkin** [comment]
@sdroege Thanks, 👍

**Comment by sdroege** [comment]
@GuillaumeGomez CI is green :)

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
