### PR TITLE
Update based on groovy gir files

### PR DESCRIPTION
**Pull request by BrainBlasted**
Part of https://github.com/gtk-rs/gir-files/pull/59

### CODE REVIEW

**Review by sdroege — APPROVED** [review]
Looks good to me, can go in after the `gir-files` PR is in. Thanks!

**Comment by sdroege** [comment]
With the `gir-files` PR merged, can you update this accordingly? And then let's get this one also merged :)

**Comment by BrainBlasted** [comment]
Updated :)

**Comment by sdroege** [comment]
Thanks, updated also for the CI failure :) Should be good to be merged now, only waiting for the CI to finish.

**Comment by sdroege** [comment]
@GuillaumeGomez CI is happy, let's get this in?

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
