### PR TITLE
Update GIR to the latest version and regenerate everything

### PR DESCRIPTION
**Pull request by sdroege**
See https://github.com/gtk-rs/gir/issues/480

### CODE REVIEW

**Comment by EPashkin** [comment]
@sdroege Thanks 
@GuillaumeGomez  👍  for this

**Comment by EPashkin** [comment]
@sdroege Can you do gdk next? This way building can be checked by us locally.

**Comment by GuillaumeGomez** [comment]
I suppose the failure is normal?

**Comment by sdroege** [comment]
Yeah, updating gdk. It's getting on my nerves that all these crates are in separate repositories instead of being in the same workspace.

**Comment by sdroege** [comment]
Sorry, no time for finishing this now. Will have to check again tomorrow or maybe later if nobody else wants to take this before.

**Comment by GuillaumeGomez** [comment]
> Yeah, updating gdk. It's getting on my nerves that all these crates are in separate repositories instead of being in the same workspace.

It was a heavy decision and I still don't regret it. It was getting way too difficult to handle.

**Comment by sdroege** [comment]
Ok actually got to finish this. Not all the events had 1000 alternatives.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
